# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

  # Puedes agregar otros eventos de activación aquí si es necesario

pool:
  vmImage: ubuntu-latest

steps:
  # Instalación y análisis de dependencias de seguridad con OWASP Dependency-Check
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'Pruebas_OWASP'
      scanPath: 'src/Task/dependency-check-build-task'
      format: 'HTML'
    displayName: 'Run Dependency Check'
  
  # Comprueba el estado de salida de Dependency Check y ejecuta pasos adicionales según sea necesario
  - script: |
      if [ $? -eq 0 ]; then
        echo "Dependency Check completed successfully."
      else
        echo "Dependency Check failed with exit code $?. Continuing pipeline execution."
        # Puedes agregar aquí pasos adicionales para manejar el fallo de Dependency Check
      fi
    displayName: 'Handle Dependency Check result'
    
  # Instalación de Node.js y ejecución de comandos npm
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
